# Site settings
title: GT-MINED NSF-GOALI Mini-site
email: david.brough.@0416gmail.com
description: |
  A mini research site to report the ongoing efforts at the Georgia Institute
  of Technology supported by the NSF-GOALI program.
baseurl: "/nsf-goali"
url: "mined-gatech.github.io"

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
  parse_block_html: true

paginate: 5

# Project/User information
gh: mined-gatech/nsf-goali
disqus: tonyfast
